---
    - name: 'requirements for brenda node'
      apt: "name={{ item }} state=installed"
      with_items:
         - python-pip
         - python-dev
         - git
         - unzip
         - libcurl4-openssl-dev
         - gcc
    - name: 'install python dependencies'
      pip: 
         name: "boto s3cmd awscli"
    - name: 'install brenda'
      pip:
         name: git+http://github.com/jamesyonan/brenda.git
         editable: false
 
